name: label-sponsor

on:
  issues:
    types:
      - 'opened'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set sponsor label
        uses: JasonEtco/is-sponsor-label-action@024ac24f8b170abce078cad4ee748852369853c8
        with:
          label: ":sparkling_heart: sponsor"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
